In [1]:
import numpy as np
import cv2
from math import ceil

In [2]:
def create_list(n: int) -> int:
  if n < 1:
    return 0
  np.random.seed(314)
  numbers = np.random.uniform(0, 100, n)
  numbers = np.round(numbers, 2)
  numbers = np.where(numbers < 10, numbers + 10, numbers)
  numbers = np.where(numbers > 90, numbers - 10, numbers)

  return int(np.min(numbers) + np.max(numbers) + np.mean(numbers))

create_list(10)

170

In [3]:
def matrix_prosessing(m: int, n: int) -> int:
  matrix = np.zeros((m, n), dtype=int)

  max_depth = ceil(min(m, n) / 2)
  max_depth = 0 if m < 2 or n < 2 else max_depth
  for i in range(max_depth, -1, -1):
    matrix[0 + i, :] = i + 1
    matrix[-(1 + i), :] = i + 1
    matrix[:, 0 + i] = i + 1
    matrix[:, -(1 + i)] = i + 1

  return int(np.sum(matrix))

matrix_prosessing(4,5)

26

In [4]:
def temperature_prosessing(n: int) -> int:
  np.random.seed(314)
  temp1, temp2 = np.random.uniform(15, 33, 30), np.random.uniform(15, 33, 30)
  temp_gen = np.hstack((temp1[temp1 > n], temp2[temp2 > n]))
  return int(temp_gen.size + np.mean(temp_gen) + np.min(temp_gen) + np.max(temp_gen) + np.std(temp_gen))


temperature_prosessing(24)


118

In [ ]:
img = cv2.imread('sea500.jpg')
img_yuv = cv2.cvtColor(img, cv2.COLOR_BGR2YUV)
img_hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
pixel = img[100, 100]
pixel_yuv = img_yuv[100, 100]
pixel_hsv = img_hsv[100, 100]

print(pixel)
print(pixel_yuv)
print(pixel_hsv)

'''
cv2.imshow('img', img)
cv2.waitKey(0)
cv2.imshow("yuv", img_yuv)
cv2.waitKey(0)
cv2.imshow("hsv", img_hsv)
cv2.waitKey(0)
img_yuv_bgr = cv2.cvtColor(img, cv2.COLOR_YUV2BGR)
img_hsv_bgr = cv2.cvtColor(img, cv2.COLOR_HSV2BGR)
cv2.imshow("yuv to bgr", img_yuv_bgr)
cv2.waitKey(0)
cv2.imshow("hsv to bgr", img_hsv_bgr)
cv2.waitKey(0)
'''


[243 233 223]
[231 134 121]
[105  21 243]


QFontDatabase: Cannot find font directory /home/oleg/study/image-processing/env/lib64/python3.13/site-packages/cv2/qt/fonts.
Note that Qt no longer ships fonts. Deploy some (from https://dejavu-fonts.github.io/ for example) or switch to fontconfig.
QFontDatabase: Cannot find font directory /home/oleg/study/image-processing/env/lib64/python3.13/site-packages/cv2/qt/fonts.
Note that Qt no longer ships fonts. Deploy some (from https://dejavu-fonts.github.io/ for example) or switch to fontconfig.
QFontDatabase: Cannot find font directory /home/oleg/study/image-processing/env/lib64/python3.13/site-packages/cv2/qt/fonts.
Note that Qt no longer ships fonts. Deploy some (from https://dejavu-fonts.github.io/ for example) or switch to fontconfig.
QFontDatabase: Cannot find font directory /home/oleg/study/image-processing/env/lib64/python3.13/site-packages/cv2/qt/fonts.
Note that Qt no longer ships fonts. Deploy some (from https://dejavu-fonts.github.io/ for example) or switch to fontconfig.
QFon

-1